version: "3"

services:
  
  backend:
    build: chat-app-backend/
    ports:
      - "3000:3000"

  frontend:
    build: chat-app-frontend/
    ports:
      - "8089:8089"
    depends_on:
      - backend